### PR TITLE
Fixed cashbandits parentheses, ifrit pincode errors

### PR DESCRIPTION
**Pull request by jweisner**

### CODE REVIEW

**Review by redned70 — APPROVED** [review]
thanks, correct bug spot and fix, pulling file

**Review by redned70 — COMMENTED** [review]
_pincode not required in non persistent expression and the logic was fixed in earlier push as it was backwards

**Review by redned70 — COMMENTED** [review]
logic was a little screwed so I have now fixed and pushing fix but you have pasted some code twice into this version as you have 2 "else" so wont pull this

**Comment by jweisner** [comment]
Oops :( I must have screwed up the copy pasta from production on that code.

**Pull request closed without merging**
